# Dependabot Configuration File

# This is a basic configuration for Dependabot version updates.
# You'll need to specify the package ecosystem, directory, and update schedule.

version: 2

# Define your package updates
updates:
  - package-ecosystem: "javascript"  # Specify the package ecosystem (e.g., JavaScript, Ruby, Python)
    directory: "/"                   # Location of package manifests within your repository
    schedule:
      interval: "weekly"             # Set the update frequency (e.g., daily, weekly)

# Additional package updates can be added here if needed.
